title: Get acitvity state success response
description: Response with test activity
code: 200
response: |
  {
    "message": "success",
    "activities": [
        {
            "activityId": "ui-test",
            "activityRun": {
              "completed": 15,
              "missed": 2,
              "total": 100
            },
            "activityRunId": "18",
            "activityState": "inProgress",
            "activityVersion": "1.1"
        },
        {
            "activityId": "default",
            "activityRun": {
              "completed": 1,
              "missed": 0,
              "total": 1
            },
            "activityRunId": "1",
            "activityState": "inProgress",
            "activityVersion": "1.2"
        }
    ]
  }
