name: Main Branch CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  flutter-tests:
    name: Test Flutter ${{ matrix.flutter_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        flutter_version: [stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@main
        with:
          channel: ${{ matrix.flutter_version }}
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: ./tool/flutter_ci_script_${{ matrix.flutter_version }}.sh
      - name: 'Upload diff-test failures'
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: Failed Screenshots for tests on flutter ${{ matrix.flutter_version }} on ${{ matrix.os }}
          path: test/**/failures/*.png
          retention-days: 5
